# Generated by Django 3.0.5 on 2020-06-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_notificationspreferences'),
        ('base', '0056_moduletutorrepartition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesNumberByAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CourseType')),
                ('groups', models.ManyToManyField(to='base.Group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Module')),
                ('possible_tutors', models.ManyToManyField(related_name='CNBA_as_possible_tutor', to='people.Tutor')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RoomType')),
                ('supp_tutors', models.ManyToManyField(related_name='CNBA_as_supp_tutor', to='people.Tutor')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CNBA_as_tutor', to='people.Tutor')),
            ],
        ),
    ]
