# Generated by Django 3.0.14 on 2021-06-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('base', '0074_scheduledcourseadditional_o2_room_id'), ('base', '0075_auto_20210601_1134'), ('base', '0076_auto_20210601_1202'), ('base', '0077_auto_20210601_1208'), ('base', '0078_deptgrafana'), ('base', '0079_auto_20210614_0902'), ('base', '0080_auto_20210614_0949'), ('base', '0081_auto_20210614_0951')]

    dependencies = [
        ('base', '0073_auto_20210426_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGrafana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_id', models.IntegerField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grafana', to='base.Room')),
            ],
        ),
        migrations.CreateModel(
            name='DeptGrafana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grafana', models.URLField(blank=True, default=None, null=True)),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grafana', to='base.Department')),
            ],
        ),
    ]
