# Generated by Django 3.0.14 on 2022-04-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_period_type_reservation_reservation_periode_reservation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id_periodicite',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='reservation_periode',
            name='period_type',
        ),
        migrations.DeleteModel(
            name='Period_type',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Reservation_periode',
        ),
        migrations.DeleteModel(
            name='Reservation_type',
        ),
    ]
