# Generated by Django 3.0.14 on 2022-06-03 13:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20220616_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('attribute_type', models.CharField(choices=[('N', 'Numeric'), ('B', 'Boolean'), ('A', 'Arraylist')], default='B', max_length=2)),
                ('array_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('default_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkRoomAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RoomAttribute')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valued_attributes', to='base.Room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='linkroomattributes',
            constraint=models.UniqueConstraint(fields=('room', 'attribute'), name='unique_room_attribute'),
        ),
    ]
