# Generated by Django 3.0.14 on 2022-05-24 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20220524_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomattribute',
            name='array_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='roomattribute',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
