# Generated by Django 3.0.14 on 2022-05-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20220524_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomattribute',
            name='default_value',
            field=models.CharField(default='False', max_length=20),
            preserve_default=False,
        ),
    ]
