# Generated by Django 3.0.14 on 2022-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20220603_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomattribute',
            name='array_values',
        ),
        migrations.RemoveField(
            model_name='roomattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='roomattribute',
            name='default_value',
        ),
        migrations.AddField(
            model_name='room',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.RoomAttribute'),
        ),
        migrations.DeleteModel(
            name='LinkRoomAttributes',
        ),
    ]
