# Generated by Django 3.0.14 on 2022-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_roomattribute_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomattribute',
            name='attribute_type',
            field=models.CharField(choices=[('N', 'Numeric'), ('B', 'Boolean'), ('A', 'Arraylist')], default='B', max_length=2),
        ),
    ]
