# Generated by Django 3.0.14 on 2022-04-26 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0085_period_type_reservation_reservation_periode_reservation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('ED', 'Each day'), ('EW', 'Each week'), ('EM', 'Each month'), ('FDW', 'First day of the week  ')], default='EW', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('ending', models.DateField()),
                ('period_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Period_type')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.BooleanField()),
                ('reservation_date', models.DateField()),
                ('start', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('id_periodicite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Reservation_periode')),
                ('reservation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Reservation_type')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationResp', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationRoom', to='base.Room')),
            ],
        ),
    ]
