# Generated by Django 3.0.14 on 2022-05-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_periode',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_periodicite',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Period_choice',
            field=models.CharField(blank=True, help_text="Only required if 'periodicity' is selected ", max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='courriel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='each_week_choice',
            field=models.CharField(blank=True, choices=[('1', 'Each week'), ('2', 'Each 2 weeks'), ('3', 'Each 3 weeks'), ('4', 'Each 4 weeks')], max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='each_x_choice',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('last', 'Last')], max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='each_y_choice',
            field=models.CharField(blank=True, choices=[('m', 'Monday'), ('tu', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday')], max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='periodicity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Reservation_type'),
        ),
        migrations.DeleteModel(
            name='Period_type',
        ),
        migrations.DeleteModel(
            name='Reservation_periode',
        ),
    ]
