# Generated by Django 3.0.14 on 2022-05-20 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220519_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPeriodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity_type', models.CharField(choices=[('BW', 'By week'), ('EM', 'Each month at the same date'), ('BM', 'By Month')], default='BW', max_length=2)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('bw_weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2), size=None)),
                ('bw_weeks_nb', models.PositiveSmallIntegerField()),
                ('bm_y_choice', models.CharField(blank=True, choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reservation_type',
            new_name='ReservationType',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='courriel',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='key',
            new_name='with_key',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Period_choice',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='each_week_choice',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='each_x_choice',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='each_y_choice',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='periodicity',
        ),
    ]
