# Generated by Django 3.0.14 on 2022-06-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220618_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='bm_x_choice',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (-2, 'Ante Last'), (-1, 'Last')], null=True),
        ),
    ]
