# Generated by Django 3.0.14 on 2022-05-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220520_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='periodicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.ReservationPeriodicity'),
        ),
    ]
