# Generated by Django 3.0.14 on 2022-05-20 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationperiodicity',
            name='bm_x_choice',
            field=models.IntegerField(blank=True, choices=[('-2', 'Ante Last'), ('-1', 'Last'), ('1', 'First')], null=True),
        ),
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='bw_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2), help_text='blabla', size=None),
        ),
    ]
