# Generated by Django 3.0.14 on 2022-05-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20220520_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
