# Generated by Django 3.0.14 on 2022-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20220520_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='bm_x_choice',
            field=models.CharField(blank=True, choices=[('AL', 'Ante Last'), ('L', 'Last'), ('F', 'First')], max_length=2, null=True),
        ),
    ]
