# Generated by Django 3.0.14 on 2022-05-23 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20220520_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end',
            field=models.TimeField(default=datetime.datetime(2022, 5, 23, 12, 47, 34, 591975)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start',
            field=models.TimeField(default=datetime.datetime(2022, 5, 23, 12, 47, 34, 591962)),
        ),
    ]
