# Generated by Django 3.0.14 on 2022-05-23 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20220523_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 23, 12, 47, 57, 451806)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 23, 12, 47, 57, 451793)),
        ),
    ]
