# Generated by Django 3.0.14 on 2022-06-02 08:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20220602_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='bw_weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('m', 'monday'), ('tu', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=2, null=True), help_text='m, tu, w, th, f', size=None),
        ),
        migrations.AlterField(
            model_name='reservationperiodicity',
            name='bw_weeks_nb',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
