version: '3'

services:
  db:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/flopedt-${BRANCH:-default}
  redis:
    image: redis:latest
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        /code/FlOpEDT/manage.py makemigrations --settings=FlOpEDT.settings.${CONFIG:-development}
        /code/FlOpEDT/manage.py migrate --settings=FlOpEDT.settings.${CONFIG:-development}
        /code/FlOpEDT/manage.py runserver 0.0.0.0:8000 --settings=FlOpEDT.settings.${CONFIG:-development}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
