version: '3'

services:
  db:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/flopedt-${BRANCH:-master}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5445:5432"
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT-6379}:6379"
  web:
    build:
      context: .
      args:
        CONFIG: development
    env_file: 
      - ./docker/env/db.env
      - ./docker/env/web.env
    environment:
      - DJANGO_SETTINGS_MODULE=FlOpEDT.settings.development
      - START_SERVER=${START_SERVER:-on}
      - DJANGO_LOADDATA
      - CONFIG=development
    entrypoint: /code/docker/script/init.sh      
    volumes:
      - .:/code
    ports:
      - "${PORT-80}:8000"
    depends_on:
      - db
      - redis
      - vue
  vue:
    build:
      dockerfile: ./Dockerfile-Vue
      args:
        USER_ID: $(id -u)
        GROUP_ID: $(id -g)
    environment:
      - YARN=serve
    volumes:
      - .:/code
    ports:
      - "8080:8000"
