version: '3'

services:
  db:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/flopedt-${BRANCH:-master}
  redis:
    image: redis:latest
  web:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: FlOpEDT.settings.${CONFIG:-development}
    command: 
      - /bin/sh
      - -c
      - |
        /code/FlOpEDT/manage.py makemigrations
        /code/FlOpEDT/manage.py migrate
        /code/FlOpEDT/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
