version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: 
      - /bin/sh
      - -c
      - |
        /code/FlOpEDT/manage.py migrate --settings=FlOpEDT.settings.${EDT_CONFIG:-development}
        /code/FlOpEDT/manage.py runserver 0.0.0.0:8000 --settings=FlOpEDT.settings.${EDT_CONFIG:-development}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
