version: '3'

services:

  memcached:
    image: memcached

  db:
    restart: always
    image: postgres
    env_file:
      - ./docker/env/db.env
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "db-backup:/backup"
    deploy:
      resources:
        limits:
          cpus: '0.50'

  nginx:
    restart: always
    image: "nginx"
    ports:
      - "${PORT-80}:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - static-volume:/static
    depends_on:
      - web

  redis:
    image: redis:latest
 
  web:
    restart: always
    image:  localhost:5000/${COMPOSE_PROJECT_NAME:-edt_pro_web}
    build: 
      context: .
      args:
        CONFIG: production    
    env_file:
      - ./docker/env/db.env
      - ./docker/env/web.env
      - ./docker/env/web.prod.env
    environment:
      - DJANGO_SETTINGS_MODULE=FlOpEDT.settings.production
      - START_SERVER=${START_SERVER:-on}
      - DJANGO_LOADDATA
      - CONFIG=production
    volumes:
      - static-volume:/code/FlOpEDT/static
    depends_on:
      - db
      - redis      
      - memcached
    entrypoint: /code/docker/script/init.sh  

volumes:
  static-volume:
  db-data:
  db-backup: