# Generated by Django 3.0.14 on 2022-12-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_courseadditional_over_time'),
        ('displayweb', '0005_auto_20210831_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakingnews',
            name='year',
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Week'),
        ),
    ]
